### ISSUE TITLE
change "I will help scientists improve the quality of their software without passing judgment."

### ISSUE THREAD

**Issue by christoph-becker** [DagstuhlEAS/draft-manifesto#3]
I suggest to replace 'scientists' in this pledge with researchers. Due to the distinctions between scientific and other research we discussed, it would make this more inclusive.

**Comment by matthewturk** [comment]
+1.  I'd also support changing to either "researchers" or "scholars".

On Fri, Nov 25, 2016 at 10:36 AM, christoph-becker <notifications@github.com

**Comment by onierstrasz** [comment]
There are about eleven such instances. Do you think they should all be changed? For me it looks like it would make sense either way.

**Comment by danielskatz** [comment]
I think researchers is better than scientists - I would change this in all places
