### ISSUE TITLE
pledges group 3: "Development and Use"?

### ISSUE THREAD

**Issue by christoph-becker** [DagstuhlEAS/draft-manifesto#4]
The third group of pledges may be better called "Development and Use", since it covers a key aspect - the use and evolution of software beyond it's initial creation. The current group of pledges seem to suggest that this is not covered at all.
(Alternatively, a fourth group may still be useful?)

**Comment by onierstrasz** [comment]
Yes, I like this proposal.

**Comment by danielskatz** [comment]
me too
